In [3]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Admin\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Admin\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Admin\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [3]:
df=pd.read_excel('EDA_Source/flight_price.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 1.8 MB

In [92]:
## now doing feature engineering my converting data object into  integer format
## first we split all the dates in date , month , year

 # we got by this 1st index of data_of_journy string i.e date
df['Date']=df['Date_of_Journey'].str.split('/').str[0]

 # we got by this 1st index of data_of_journy string i.e Month
df['Month']=df['Date_of_Journey'].str.split('/').str[1]

In [93]:

 # we got by this 2th index of data_of_journy string i.e Year
df['Year']=df['Date_of_Journey'].str.split('/').str[2]

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), str(10)
memory usage: 2.0 MB

In [94]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Total_Stops,Additional_Info,Price,Departure_hour,Departure_min,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Min,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,0,No info,3897,22,20,2,50,1,10,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,2,No info,7662,5,50,7,25,13,15,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,2,No info,13882,9,25,19,0,4,25,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,1,No info,6218,18,5,5,25,23,30,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,1,No info,13302,16,50,4,45,21,35,01,03,2019

In [95]:
## Now we convert that all dates objects into integer

df['Date']=df['Date'].astype(int)
df['Month']=df['Month'].astype(int)
df['Year']=df['Year'].astype(int)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Total_Stops      10683 non-null  int64
 5   Additional_Info  10683 non-null  str
 6   Price            10683 non-null  int64
 7   Departure_hour   10683 non-null  int64
 8   Departure_min    10683 non-null  int64
 9   Duration_Hour    10683 non-null  int64
 10  Duration_Min     10683 non-null  int64
 11  Arrival_Hour     10683 non-null  int64
 12  Arrival_Min      10683 non-null  int64
 13  Date             10683 non-null  int64
 14  Month            10683 non-null  int64
 15  Year             10683 non-null  int64
dtypes: int64(11), str(5)
memory usage: 1.8 MB

In [96]:
## Now we drop Date_of_journy column 
df.drop('Date_of_Journey',axis=1,inplace=True)

In [97]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Departure_hour,Departure_min,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Min,Date,Month,Year
0,IndiGo,Banglore,New Delhi,0,No info,3897,22,20,2,50,1,10,24,3,2019
1,Air India,Kolkata,Banglore,2,No info,7662,5,50,7,25,13,15,1,5,2019
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,25,19,0,4,25,9,6,2019
3,IndiGo,Kolkata,Banglore,1,No info,6218,18,5,5,25,23,30,12,5,2019
4,IndiGo,Banglore,New Delhi,1,No info,13302,16,50,4,45,21,35,1,3,2019

In [75]:
df['Arrival_Time']=df['Arrival_Time'].apply(lambda x:x.split(' ')[0])

In [76]:
df['Arrival_Hour']=df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Min']=df['Arrival_Time'].str.split(':').str[1]

In [77]:
df.drop('Arrival_Time',axis=1, inplace=True)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Duration         10683 non-null  str
 6   Total_Stops      10682 non-null  str
 7   Additional_Info  10683 non-null  str
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_Hour     10683 non-null  object
 13  Arrival_Min      10683 non-null  object
dtypes: int64(4), object(2), str(8)
memory usage: 1.9+ MB

In [78]:
df['Arrival_Hour']=df['Arrival_Hour'].astype(int)
df['Arrival_Min']=df['Arrival_Min'].astype(int)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Duration         10683 non-null  str
 6   Total_Stops      10682 non-null  str
 7   Additional_Info  10683 non-null  str
 8   Price            10683 non-null  int64
 9   Date             10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_Hour     10683 non-null  int64
 13  Arrival_Min      10683 non-null  int64
dtypes: int64(6), str(8)
memory usage: 1.9 MB

In [79]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,Departure_hour,Departure_min,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,22,20,2,50,1,10
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,5,50,7,25,13,15
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,25,19,0,4,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,18,5,5,25,23,30
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,16,50,4,45,21,35

In [26]:
## now convert departure time in int
df['Departure_hour']=df['Dep_Time'].str.split(':').str[0]
df['Departure_min']=df['Dep_Time'].str.split(':').str[1]

In [27]:
df['Departure_hour']=df['Departure_hour'].astype(int)
df['Departure_min']=df['Departure_min'].astype(int)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Departure_hour   10683 non-null  int64
 12  Departure_min    10683 non-null  int64
dtypes: int64(3), str(10)
memory usage: 2.0 MB

In [31]:
df.drop('Dep_Time',axis=1,inplace=True)

In [32]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Departure_hour,Departure_min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,01:10 22 Mar,2h 50m,non-stop,No info,3897,22,20
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,13:15,7h 25m,2 stops,No info,7662,5,50
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,04:25 10 Jun,19h,2 stops,No info,13882,9,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,23:30,5h 25m,1 stop,No info,6218,18,5
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,21:35,4h 45m,1 stop,No info,13302,16,50

In [67]:
df['Duration_Hour']=df['Duration'].str.split('h').str[0]
df['Duration_Min']=df['Duration'].str.split(' ').str[1].str.replace('m','',regex=False)

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Arrival_Time     10683 non-null  str
 6   Duration         10683 non-null  str
 7   Total_Stops      10682 non-null  str
 8   Additional_Info  10683 non-null  str
 9   Price            10683 non-null  int64
 10  Departure_hour   10683 non-null  int64
 11  Departure_min    10683 non-null  int64
 12  Duration_Hour    10683 non-null  object
 13  Duration_Min     9651 non-null   object
dtypes: int64(3), object(2), str(9)
memory usage: 2.0+ MB

In [ ]:
df['Duration_Hour'] = df['Duration'].str.extract(r'(\d+)h').fillna(0).astype(int) #r'(\d+)h' extracts the digits before h.
df['Duration_Min'] = df['Duration'].str.extract(r'(\d+)m').fillna(0).astype(int)  #r'(\d+)m' extracts the digits before m.

In [73]:
df.drop('Duration',axis=1,inplace=True)

In [80]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,Departure_hour,Departure_min,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,22,20,2,50,1,10
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,5,50,7,25,13,15
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,No info,13882,9,25,19,0,4,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,1 stop,No info,6218,18,5,5,25,23,30
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,1 stop,No info,13302,16,50,4,45,21,35

In [81]:
df['Total_Stops'].unique()

<ArrowStringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [83]:
df[df['Total_Stops'].isnull()]

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,Departure_hour,Departure_min,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Min
9039,Air India,6/05/2019,Delhi,Cochin,NaN,NaN,No info,7480,9,45,23,40,9,25

In [85]:
df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3, np.nan:0, '4 stops':0})

In [86]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Date_of_Journey, Source, Destination, Route, Total_Stops, Additional_Info, Price, Departure_hour, Departure_min, Duration_Hour, Duration_Min, Arrival_Hour, Arrival_Min]
Index: []

In [87]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Total_Stops,Additional_Info,Price,Departure_hour,Departure_min,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Min
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,0,No info,3897,22,20,2,50,1,10
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,5,50,7,25,13,15
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,2,No info,13882,9,25,19,0,4,25
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,1,No info,6218,18,5,5,25,23,30
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,1,No info,13302,16,50,4,45,21,35

In [88]:
df.drop('Route',axis=1,inplace=True)

In [98]:
df.head(3)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Departure_hour,Departure_min,Duration_Hour,Duration_Min,Arrival_Hour,Arrival_Min,Date,Month,Year
0,IndiGo,Banglore,New Delhi,0,No info,3897,22,20,2,50,1,10,24,3,2019
1,Air India,Kolkata,Banglore,2,No info,7662,5,50,7,25,13,15,1,5,2019
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,25,19,0,4,25,9,6,2019

In [5]:
df['Airline'].unique()

<ArrowStringArray>
[                           'IndiGo',                         'Air India',
                       'Jet Airways',                          'SpiceJet',
                 'Multiple carriers',                             'GoAir',
                           'Vistara',                          'Air Asia',
           'Vistara Premium economy',              'Jet Airways Business',
 'Multiple carriers Premium economy',                            'Trujet']
Length: 12, dtype: str

In [6]:
df[df['Airline'].isnull()]

Empty DataFrame
Columns: [Airline, Date_of_Journey, Source, Destination, Route, Dep_Time, Arrival_Time, Duration, Total_Stops, Additional_Info, Price]
Index: []

In [7]:
!pip install sklearn

Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'sklearn' when getting requirements to build wheel

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
encoder=OneHotEncoder()

In [10]:
encoder.fit_transform(df[['Airline','Source','Destination']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(10683, 23))

In [11]:
pd.DataFrame(encoder.fit_transform(df[['Airline','Source','Destination']]).toarray(),columns=encoder.get_feature_names_out())

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10679,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10680,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10681,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10682,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0